baseURL = 'https://example.org/'
defaultContentLanguage = 'en-us'
theme = 'baccscinema'

[languages]
  [languages.en-us]
    languageCode = 'en-us'
    languageName = 'English'
    title = 'BACCS Cinema'
    weight = 1

  [languages.zh-cn]
    languageCode = 'zh-cn'
    languageName = '简体中文'
    title = 'BACCS 电影院'
    weight = 2
